### ISSUE TITLE
Define input and output files path

### ISSUE THREAD

**Issue by FabioTS** [novaweb-mobi/nova-api#39]
**Is your feature request related to a problem? Please describe.**
I can only generate API files within the root directory where the server file is located. I want to apply a structured code in my project but i can't

**Describe the solution you'd like**
I want to have environment variables so i can define:

- ENTITIES_INPUT_PATH: path to my entities files like `./src/entities`
- ENTITIES_DAO_INPUT_PATH: path to my entities DAO files like `./src/dao`
- API_OUTPUT_PATH: path to output the auto generated '*_api.py' files like `./src/api`
- YAML_OUTPUT_PATH: path to output the auto generated '*_api.yml' files like `./src/api/yaml`

**Describe alternatives you've considered**
Could not find any workarround since every one i've tryed crashed

**Additional context**
In the Domain Driven Design code aproach, there are several folder in the project context. It would be great if NovaAPI supports such architectures.

**Comment by MatTerra** [comment]
This can be easily implemented on the api generation command by adding more command line options as -o or --output-api and --output-swagger and --src-dir or --input-path. At runtime, the APIS env variable may be used with the full relative path of the yml and from the swagger the operationId can be changed to correctly point to your api module.

**Comment by MatTerra** [comment]
@guilhermelionzo, this is the issue I discussed with you and we ended up going for the solution pointed by me. This is the second time in a short period of time we're affected by it. Probably is time to give it more attention. @FabioTS @titosilva

**Comment by MatTerra** [comment]
\nostale

**Comment by MatTerra** [comment]
not stale
